Fein

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,36 +6,34 @@ on:
       - main
 
 jobs:
-    deploy:
-      name: Deploy to Self-Hosted Runner
-      runs-on: self-hosted
-
+  deploy:
+    name: Deploy to Self-Hosted Runner
+    runs-on: self-hosted
 
     steps:
-     - name: Checkout Code
-       uses: actions/checkout@v3
-    
-    - name: Pull latest changes
-      run: git pull --no-edit origin main
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: "22" 
+      - name: Pull latest changes
+        run: git pull --no-edit origin main
 
-    - name: Install dependencies
-      working-directory: ./
-      run: npm install
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "22"
 
-    - name: Reload with PM2
-      run: |
-        echo "Reloading server"
-        pm2 reload server --update-env
+      - name: Install dependencies
+        working-directory: ./
+        run: npm install
 
-    - name: Verify PM2 status
-      run: |
-        pm2 status
-        if pm2 list | grep -qE "errored|stopped"; then
-          echo "One of more processes has errored or stopped"
-          exit 1
-        fi  
+      - name: Reload with PM2
+        run: |
+          echo "Reloading server"
+          pm2 reload server --update-env
+
+      - name: Verify PM2 status
+        run: |
+          pm2 status
+          if pm2 list | grep -qE "errored|stopped"; then
+            echo "One or more processes have errored or stopped"
+            exit 1
